/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/requests/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 장소 등록 요청 */
        post: operations["requestPlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이벤트 등록 요청 */
        post: operations["requestEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 장소 목록 조회 */
        get: operations["getPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 장소 상세 조회 */
        get: operations["getPlace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 이벤트 목록 조회 */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 이벤트 상세 조회 */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 카테고리 목록 조회 */
        get: operations["getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CategoryResponse: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        ApiResponseListCategoryResponse: {
            data: components["schemas"]["CategoryResponse"][];
        };
        PlaceRequestInput: {
            /** @enum {string} */
            requestType: "NEW" | "UPDATE";
            /** Format: int64 */
            placeId?: number;
            name?: string;
            address?: string;
            addressDetail?: string;
            lat?: number;
            lng?: number;
            categoryIds?: number[];
            hoursText?: string;
            closedDays?: string;
            brandsYarn?: string;
            brandsNeedle?: string;
            brandsNotions?: string;
            instagramUrl?: string;
            websiteUrl?: string;
            naverMapUrl?: string;
            tags?: string;
            note?: string;
        };
        EventRequestInput: {
            title: string;
            /** @enum {string} */
            eventType: "TESTER_RECRUIT" | "SALE" | "EVENT_POPUP";
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate?: string;
            locationText?: string;
            description?: string;
        };
        /** @description 등록 요청 응답 */
        RequestResponse: {
            /**
             * Format: int64
             * @description 생성된 요청 ID
             * @example 1
             */
            id: number;
        };
        ApiResponseRequestResponse: {
            data: components["schemas"]["RequestResponse"];
        };
        CategoryInfo: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        TagInfo: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        BrandInfo: {
            /** Format: int64 */
            id: number;
            name: string;
            type: string;
        };
        /** @description 장소 목록 응답 */
        PlaceListResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            region: string;
            district: string;
            address: string;
            lat?: number;
            lng?: number;
            status: string;
            categories: components["schemas"]["CategoryInfo"][];
            tags: components["schemas"]["TagInfo"][];
            instagramUrl?: string;
            naverMapUrl?: string;
        };
        ApiResponseListPlaceListResponse: {
            data: components["schemas"]["PlaceListResponse"][];
        };
        /** @description 장소 상세 응답 */
        PlaceDetailResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            region: string;
            district: string;
            address: string;
            lat?: number;
            lng?: number;
            hoursText?: string;
            closedDays?: string;
            description?: string;
            status: string;
            categories: components["schemas"]["CategoryInfo"][];
            tags: components["schemas"]["TagInfo"][];
            brands: components["schemas"]["BrandInfo"][];
            instagramUrl?: string;
            websiteUrl?: string;
            naverMapUrl?: string;
        };
        ApiResponsePlaceDetailResponse: {
            data: components["schemas"]["PlaceDetailResponse"];
        };
        EventListResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            eventType: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate?: string;
            locationText?: string;
            lat?: number;
            lng?: number;
            active: boolean;
            links?: string;
        };
        ApiResponseListEventListResponse: {
            data: components["schemas"]["EventListResponse"][];
        };
        EventDetailResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            description?: string;
            eventType: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate?: string;
            /** Format: int64 */
            placeId?: number;
            locationText?: string;
            lat?: number;
            lng?: number;
            active: boolean;
            links?: string;
        };
        ApiResponseEventDetailResponse: {
            data: components["schemas"]["EventDetailResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    requestPlace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceRequestInput"];
            };
        };
        responses: {
            /** @description 요청 등록 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseRequestResponse"];
                };
            };
            /** @description 유효하지 않은 요청 값 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseRequestResponse"];
                };
            };
        };
    };
    requestEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequestInput"];
            };
        };
        responses: {
            /** @description 요청 등록 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseRequestResponse"];
                };
            };
            /** @description 유효하지 않은 요청 값 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseRequestResponse"];
                };
            };
        };
    };
    getPlaces: {
        parameters: {
            query?: {
                /** @description 검색어 (장소명, 주소, 태그, 브랜드 통합 검색) */
                keyword?: string;
                /** @description 지역 필터 (예: 서울, 경기) */
                region?: string;
                /** @description 카테고리 ID */
                categoryId?: number;
                /** @description 태그 ID */
                tagId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseListPlaceListResponse"];
                };
            };
        };
    };
    getPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 장소 ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePlaceDetailResponse"];
                };
            };
            /** @description 존재하지 않는 장소 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponsePlaceDetailResponse"];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: {
                /** @description 이벤트 타입 (TESTER_RECRUIT, SALE, EVENT_POPUP) */
                eventType?: "TESTER_RECRUIT" | "SALE" | "EVENT_POPUP";
                /** @description 활성 여부 (기본값: true) */
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseListEventListResponse"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 이벤트 ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseEventDetailResponse"];
                };
            };
            /** @description 존재하지 않는 이벤트 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseEventDetailResponse"];
                };
            };
        };
    };
    getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseListCategoryResponse"];
                };
            };
        };
    };
}
