/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/requests/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 장소 등록 요청 */
        post: operations["requestPlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이벤트 등록 요청 */
        post: operations["requestEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 장소 리뷰 목�� 조회 */
        get: operations["getPlaceReviews"];
        put?: never;
        /** 장소 리뷰 작성 */
        post: operations["createPlaceReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 이벤트 리뷰 목록 조회 */
        get: operations["getEventReviews"];
        put?: never;
        /** 이벤트 리뷰 작성 */
        post: operations["createEventReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 장소 목록 조회 */
        get: operations["getPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 장소 상세 조회 */
        get: operations["getPlace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 이벤트 목록 조회 */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 이벤트 상세 조회 */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 카테고리 목록 조회 */
        get: operations["getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 타입별 브랜드 목록 조회 */
        get: operations["getBrands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 리뷰 삭제 (비밀번호 검증) */
        delete: operations["deleteReview"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PlaceRequestInput: {
            /** @enum {string} */
            requestType: "NEW" | "UPDATE";
            /** Format: int64 */
            placeId?: number;
            name?: string;
            address?: string;
            addressDetail?: string;
            lat?: number;
            lng?: number;
            categoryIds?: number[];
            categoryText?: string;
            hoursText?: string;
            closedDays?: string;
            brandYarnIds?: number[];
            brandsYarn?: string;
            brandNeedleIds?: number[];
            brandsNeedle?: string;
            brandNotionsIds?: number[];
            brandsNotions?: string;
            brandPatternbookIds?: number[];
            brandsPatternbook?: string;
            instagramUrl?: string;
            websiteUrl?: string;
            naverMapUrl?: string;
            tags?: string;
            note?: string;
        };
        ApiResponseRequestResponse: {
            data: components["schemas"]["RequestResponse"];
        };
        /** @description 등록 요청 응답 */
        RequestResponse: {
            /**
             * Format: int64
             * @description 생성된 요청 ID
             * @example 1
             */
            id: number;
        };
        EventRequestInput: {
            title: string;
            /** @enum {string} */
            eventType: "TESTER_RECRUIT" | "SALE" | "EVENT_POPUP";
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate?: string;
            locationText?: string;
            description?: string;
        };
        /** @description 리뷰 작성 요청 */
        ReviewCreateRequest: {
            /**
             * @description 닉네임
             * @example 뜨개하는고양이
             */
            nickname: string;
            /**
             * @description 이메일
             * @example cat@example.com
             */
            email: string;
            /**
             * @description 비밀번호 (삭제 시 사용, 4~20자)
             * @example 1234
             */
            password: string;
            /**
             * @description 리뷰 내용
             * @example 실 종류가 다양하고 사장님이 친절해요!
             */
            content: string;
        };
        ApiResponseReviewResponse: {
            data: components["schemas"]["ReviewResponse"];
        };
        /** @description 리뷰 응답 */
        ReviewResponse: {
            /**
             * Format: int64
             * @description 리뷰 ID
             * @example 1
             */
            id: number;
            /**
             * @description 닉네임
             * @example 뜨개하는고양이
             */
            nickname: string;
            /** @description 리뷰 내용 */
            content: string;
            /**
             * Format: date-time
             * @description 작성일시
             */
            createdAt: string;
        };
        ApiResponseListPlaceListResponse: {
            data: components["schemas"]["PlaceListResponse"][];
        };
        /** @description 브랜드 요약 정보 */
        BrandDto: {
            /**
             * Format: int64
             * @description 브랜드 ID
             * @example 1
             */
            id: number;
            /**
             * @description 브랜드명
             * @example 드미트리아
             */
            name: string;
            /**
             * @description 브랜드 유형
             * @example YARN
             */
            type: string;
        };
        /** @description 카테고리 요약 정보 */
        CategoryDto: {
            /**
             * Format: int64
             * @description 카테고리 ID
             * @example 1
             */
            id: number;
            /**
             * @description 카테고리명
             * @example 공방
             */
            name: string;
        };
        /** @description 장소 목록 응답 */
        PlaceListResponse: {
            /**
             * Format: int64
             * @description 장소 ID
             * @example 1
             */
            id: number;
            /**
             * @description 장소명
             * @example 실과 바늘
             */
            name: string;
            /**
             * @description 지역
             * @example 서울
             */
            region: string;
            /**
             * @description 동네
             * @example 성수
             */
            district: string;
            /**
             * @description 주소
             * @example 서울 성동구 연무장길 1
             */
            address: string;
            /** @description 위도 */
            lat?: number;
            /** @description 경도 */
            lng?: number;
            /**
             * @description 운영 상태
             * @example OPEN
             */
            status: string;
            /** @description 카테고리 목록 */
            categories: components["schemas"]["CategoryDto"][];
            /** @description 태그 목록 */
            tags: components["schemas"]["TagDto"][];
            /** @description 브랜드 목록 */
            brands: components["schemas"]["BrandDto"][];
            /** @description 인스타그램 URL */
            instagramUrl?: string;
            /** @description 네이버 지도 URL */
            naverMapUrl?: string;
        };
        /** @description 태그 요약 정보 */
        TagDto: {
            /**
             * Format: int64
             * @description 태그 ID
             * @example 1
             */
            id: number;
            /**
             * @description 태그명
             * @example 초보환영
             */
            name: string;
        };
        ApiResponseListReviewResponse: {
            data: components["schemas"]["ReviewResponse"][];
        };
        ApiResponsePlaceDetailResponse: {
            data: components["schemas"]["PlaceDetailResponse"];
        };
        /** @description 장소 상세 응답 */
        PlaceDetailResponse: {
            /**
             * Format: int64
             * @description 장소 ID
             * @example 1
             */
            id: number;
            /**
             * @description 장소명
             * @example 실과 바늘
             */
            name: string;
            /**
             * @description 지역
             * @example 서울
             */
            region: string;
            /**
             * @description 동네
             * @example 성수
             */
            district: string;
            /**
             * @description 주소
             * @example 서울 성동구 연무장길 1
             */
            address: string;
            /** @description 위도 */
            lat?: number;
            /** @description 경도 */
            lng?: number;
            /**
             * @description 영업시간 텍스트
             * @example 화~금 10:00-19:00
             */
            hoursText?: string;
            /**
             * @description 휴무일
             * @example 월요일
             */
            closedDays?: string;
            /** @description 장소 설명 */
            description?: string;
            /**
             * @description 운영 상태
             * @example OPEN
             */
            status: string;
            /** @description 카테고리 목록 */
            categories: components["schemas"]["CategoryDto"][];
            /** @description 태그 목록 */
            tags: components["schemas"]["TagDto"][];
            /** @description 브랜드 목록 */
            brands: components["schemas"]["BrandDto"][];
            /** @description 인스타그램 URL */
            instagramUrl?: string;
            /** @description 웹사이트 URL */
            websiteUrl?: string;
            /** @description 네이버 지도 URL */
            naverMapUrl?: string;
            /** @description 활성 이벤트 목록 */
            events: components["schemas"]["PlaceEventDto"][];
        };
        /** @description 장소에 연결된 이벤트 요약 정보 */
        PlaceEventDto: {
            /**
             * Format: int64
             * @description 이벤트 ID
             * @example 10
             */
            id: number;
            /**
             * @description 이벤트 제목
             * @example 봄 시즌 클래스 모집
             */
            title: string;
            /**
             * @description 이벤트 유형
             * @example TESTER_RECRUIT
             */
            eventType: string;
            /**
             * Format: date
             * @description 시작일
             * @example 2026-04-15
             */
            startDate: string;
            /**
             * Format: date
             * @description 종료일
             * @example 2026-05-10
             */
            endDate?: string;
            /**
             * @description 활성 여부
             * @example true
             */
            active: boolean;
            /** @description 관련 링크 */
            links?: string;
        };
        ApiResponseListEventListResponse: {
            data: components["schemas"]["EventListResponse"][];
        };
        /** @description 이벤트 목록 응답 */
        EventListResponse: {
            /**
             * Format: int64
             * @description 이벤트 ID
             * @example 1
             */
            id: number;
            /**
             * @description 이벤트 제목
             * @example 봄맞이 뜨개 마켓
             */
            title: string;
            /**
             * @description 이벤트 유형
             * @example POPUP
             */
            eventType: string;
            /**
             * Format: date
             * @description 시작일
             */
            startDate: string;
            /**
             * Format: date
             * @description 종료일
             */
            endDate?: string;
            /** @description 장소 텍스트 */
            locationText?: string;
            /** @description 위도 */
            lat?: number;
            /** @description 경도 */
            lng?: number;
            /** @description 활성 여부 */
            active: boolean;
            /** @description 관련 링크 */
            links?: string;
        };
        ApiResponseEventDetailResponse: {
            data: components["schemas"]["EventDetailResponse"];
        };
        /** @description 이벤트 상세 응답 */
        EventDetailResponse: {
            /**
             * Format: int64
             * @description 이벤트 ID
             * @example 1
             */
            id: number;
            /**
             * @description 이벤트 제목
             * @example 봄맞이 뜨개 마켓
             */
            title: string;
            /** @description 이벤트 설명 */
            description?: string;
            /**
             * @description 이벤트 유형
             * @example POPUP
             */
            eventType: string;
            /**
             * Format: date
             * @description 시작일
             */
            startDate: string;
            /**
             * Format: date
             * @description 종료일
             */
            endDate?: string;
            /**
             * Format: int64
             * @description 연결된 장소 ID
             */
            placeId?: number;
            /** @description 장소 텍스트 */
            locationText?: string;
            /** @description 위도 */
            lat?: number;
            /** @description 경도 */
            lng?: number;
            /** @description 활성 여부 */
            active: boolean;
            /** @description 관련 링크 */
            links?: string;
        };
        ApiResponseListCategoryResponse: {
            data: components["schemas"]["CategoryResponse"][];
        };
        /** @description 카테고리 응답 */
        CategoryResponse: {
            /**
             * Format: int64
             * @description 카테고리 ID
             * @example 1
             */
            id: number;
            /**
             * @description 카테고리명
             * @example 뜨개카페
             */
            name: string;
        };
        ApiResponseListBrandTypeGroup: {
            data: components["schemas"]["BrandTypeGroup"][];
        };
        /** @description 브랜드 항목 */
        BrandItem: {
            /**
             * Format: int64
             * @description 브랜드 ID
             * @example 1
             */
            id: number;
            /**
             * @description 브랜드명
             * @example 산네스간
             */
            name: string;
        };
        /** @description 브랜드 타입 그룹 */
        BrandTypeGroup: {
            /**
             * @description 브랜드 타입
             * @example YARN
             */
            type: string;
            /** @description 브랜드 목록 */
            brands: components["schemas"]["BrandItem"][];
        };
        /** @description 리뷰 삭제 요청 */
        ReviewDeleteRequest: {
            /**
             * @description 비밀번호
             * @example 1234
             */
            password: string;
        };
        ApiResponse: {
            data: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    requestPlace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceRequestInput"];
            };
        };
        responses: {
            /** @description 요청 등록 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRequestResponse"];
                };
            };
            /** @description 유효하지 않은 요청 값 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRequestResponse"];
                };
            };
        };
    };
    requestEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequestInput"];
            };
        };
        responses: {
            /** @description 요청 등록 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRequestResponse"];
                };
            };
            /** @description 유효하지 않은 요청 값 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRequestResponse"];
                };
            };
        };
    };
    getPlaceReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 장소 ID */
                placeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListReviewResponse"];
                };
            };
        };
    };
    createPlaceReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 장소 ID */
                placeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreateRequest"];
            };
        };
        responses: {
            /** @description 작성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReviewResponse"];
                };
            };
            /** @description 존재하지 않는 장소 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReviewResponse"];
                };
            };
        };
    };
    getEventReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 이벤트 ID */
                eventId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListReviewResponse"];
                };
            };
        };
    };
    createEventReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 이벤트 ID */
                eventId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreateRequest"];
            };
        };
        responses: {
            /** @description 작성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReviewResponse"];
                };
            };
            /** @description 존재하지 않는 이벤트 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReviewResponse"];
                };
            };
        };
    };
    getPlaces: {
        parameters: {
            query?: {
                /** @description 검색어 (장소명, 주소, 태그, 브랜드 통합 검색) */
                keyword?: string;
                /** @description 지역 필터 (예: 서울, 경기) */
                region?: string;
                /** @description 카테고리 ID */
                categoryId?: number;
                /** @description 태그 ID */
                tagId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPlaceListResponse"];
                };
            };
        };
    };
    getPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 장소 ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePlaceDetailResponse"];
                };
            };
            /** @description 존재하지 않는 장소 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePlaceDetailResponse"];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: {
                /** @description 이벤트 타입 (TESTER_RECRUIT, SALE, EVENT_POPUP) */
                eventType?: "TESTER_RECRUIT" | "SALE" | "EVENT_POPUP";
                /** @description 활성 여부 (기본값: true) */
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListEventListResponse"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 이벤트 ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEventDetailResponse"];
                };
            };
            /** @description 존재하지 않는 이벤트 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseEventDetailResponse"];
                };
            };
        };
    };
    getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCategoryResponse"];
                };
            };
        };
    };
    getBrands: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListBrandTypeGroup"];
                };
            };
        };
    };
    deleteReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ���뷰 ID */
                reviewId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDeleteRequest"];
            };
        };
        responses: {
            /** @description 삭제 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
            /** @description 비밀번호 불일치 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
            /** @description 존재하지 ��는 리뷰 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
}
